# These are supported funding model platforms
# 支援的贊助平台

github: [Rich627]
# patreon: # your_patreon_username
# open_collective: # your_open_collective_username
# ko_fi: # your_ko_fi_username
# buy_me_a_coffee: # your_buy_me_a_coffee_username
# custom: ["https://your-custom-link.com"]
