name: SmartCard
options:
  bundleIdPrefix: com.smartcard
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

# Firebase package - uncomment when ready to use
# packages:
#   Firebase:
#     url: https://github.com/firebase/firebase-ios-sdk
#     version: 10.29.0

targets:
  SmartCard:
    type: application
    platform: iOS
    sources:
      - path: SmartCard
        excludes:
          - "**/.DS_Store"
          - "**/FirebaseService.swift"
          - "**/AuthService.swift"
          - "**/AuthView.swift"
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_BUNDLE_IDENTIFIER: com.smartcard.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSCameraUsageDescription: "SmartCard uses the camera to scan receipts for quick transaction entry."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "SmartCard accesses your photo library to import receipt images."
        INFOPLIST_KEY_CFBundleDisplayName: "SmartCard"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.finance"
    resources:
      - path: SmartCard/Resources/Assets.xcassets
      - path: SmartCard/Resources/Preview Content
    dependencies:
      - target: SmartCardWidget
        embed: true
    entitlements:
      path: SmartCard/SmartCard.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.smartcard.app
    # Uncomment when Firebase is configured:
    # dependencies:
    #   - package: Firebase
    #     product: FirebaseAuth
    #   - package: Firebase
    #     product: FirebaseFirestore

  SmartCardTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SmartCardTests
    dependencies:
      - target: SmartCard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.smartcard.app.tests
        GENERATE_INFOPLIST_FILE: YES

  SmartCardWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: SmartCardWidget
    info:
      path: SmartCardWidget/Info.plist
      properties:
        CFBundleDisplayName: SmartCard Widget
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.smartcard.app.widget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_ENTITLEMENTS: SmartCardWidget/SmartCardWidget.entitlements
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
