blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/Rich627/SmartCard/discussions
    about: Ask questions and discuss ideas here
  - name: Documentation
    url: https://github.com/Rich627/SmartCard/blob/main/docs/README_EN.md
    about: Check out our documentation
